### ISSUE TITLE
[EPIC] Sunflower

### ISSUE THREAD

**Issue by vieirafrancisco** [vieirafrancisco/sunflower#2]
## Sunflower
- [ ] Criar Dockerfile e docker-compose
- [ ] Subir instância de postgres
- [ ] Subir instância de redis para o `request-cache`
- [ ] Implementar paginação no método `load_product_reviews`
- [ ] Criar documentação
- [ ] Criar sistema de prioridade de produtos baseados na quantidade de reviews

## Airflow
- [ ] Criar repositóro
- [ ] Criar Docker e docker-compose
- [ ] Criar DAG para executar o `load_product_reviews` (`@once` por enquanto)
